package iconst

const ( // product model code
	PRODUCT_MODEL_VOUCHER        = "PRODUCT_MODEL_VOUCHER"
	PRODUCT_MODEL_MOBILE_CARD    = "PRODUCT_MODEL_MOBILE_CARD"
	PRODUCT_MODEL_MOBILE_SERVICE = "PRODUCT_MODEL_MOBILE_SERVICE"
	PRODUCT_MODEL_MOBILE_TOPUP   = "PRODUCT_MODEL_MOBILE_TOPUP"
	PRODUCT_MODEL_POINT_PACKAGE  = "PRODUCT_MODEL_POINT_PACKAGE"
)

const ( // STATUS product
	PRODUCT_STATUS_ACCEPTED = "PRODUCT_STATUS_ACCEPTED"
	PRODUCT_STATUS_PENDING  = "PRODUCT_STATUS_PENDING"
	PRODUCT_STATUS_IN_TRASH = "PRODUCT_STATUS_IN_TRASH"
	PRODUCT_STATUS_DRAFT    = "PRODUCT_STATUS_DRAFT"
	PRODUCT_STATUS_REJECTED = "PRODUCT_STATUS_REJECTED"
)

const ( // STATUS product Point
	PRODUCT_POINT_PACKAGE_STATUS_ACCEPTED = "PRODUCT_POINT_PACKAGE_STATUS_ACCEPTED"
)

const ( // STATUS product Mobile
	PRODUCT_MOBILE_SERVICE_STATUS_ACCEPTED = "PRODUCT_MOBILE_SERVICE_STATUS_ACCEPTED"
	PRODUCT_MOBILE_TOPUP_STATUS_ACCEPTED   = "PRODUCT_MOBILE_TOPUP_STATUS_ACCEPTED"
	PRODUCT_MOBILE_CARD_STATUS_ACCEPTED    = "PRODUCT_MOBILE_CARD_STATUS_ACCEPTED"
	PRODUCT_MOBILE_CARD_STATUS_DRAFT       = "PRODUCT_MOBILE_CARD_STATUS_DRAFT"
)

var MapProductModel = map[string]struct{}{
	PRODUCT_MODEL_VOUCHER:        {},
	PRODUCT_MODEL_MOBILE_CARD:    {},
	PRODUCT_MODEL_MOBILE_SERVICE: {},
	PRODUCT_MODEL_MOBILE_TOPUP:   {},
	PRODUCT_MODEL_POINT_PACKAGE:  {},
}

var MapProductStatus = map[string]struct{}{
	PRODUCT_STATUS_ACCEPTED: {},
	PRODUCT_STATUS_PENDING:  {},
	PRODUCT_STATUS_IN_TRASH: {},
	PRODUCT_STATUS_DRAFT:    {},
	PRODUCT_STATUS_REJECTED: {},
}

var MapProductPoint = map[string]struct{}{
	PRODUCT_POINT_PACKAGE_STATUS_ACCEPTED: {},
}

var MapProductMobileStatus = map[string]struct{}{
	PRODUCT_MOBILE_SERVICE_STATUS_ACCEPTED: {},
	PRODUCT_MOBILE_TOPUP_STATUS_ACCEPTED:   {},
	PRODUCT_MOBILE_CARD_STATUS_ACCEPTED:    {},
	PRODUCT_MOBILE_CARD_STATUS_DRAFT:       {},
}

var MapProductModelStatusAccepted = map[string]string{
	PRODUCT_MODEL_MOBILE_CARD:    PRODUCT_MOBILE_CARD_STATUS_ACCEPTED,
	PRODUCT_MODEL_MOBILE_SERVICE: PRODUCT_MOBILE_SERVICE_STATUS_ACCEPTED,
	PRODUCT_MODEL_MOBILE_TOPUP:   PRODUCT_MOBILE_TOPUP_STATUS_ACCEPTED,
	PRODUCT_MODEL_POINT_PACKAGE:  PRODUCT_POINT_PACKAGE_STATUS_ACCEPTED,
}
