// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package http_server

import (
	"github.com/huydq/gokits/libs/transport/http"
	"github.com/huydq/gokits/shared/core/biz/healthz"
	"github.com/huydq/order-service/app/core/repository"
	"github.com/huydq/order-service/app/core/service"
	"github.com/huydq/order-service/transport/http/handler"
	"github.com/huydq/order-service/transport/http/server"
)

// Injectors from wire.go:

func wireApp(httpServer *httpserver.HttpServer, orderClient repository.OrderPostgresClient) (*server.OrderPublicServer, error) {
	healthZBiz := healthz.NewHealthZBiz(httpServer)
	orderRepository := repository.NewOrderRepository(orderClient)
	orderService := service.NewOrderService(orderRepository)
	orderHandler := order_handler.NewOrderHandler(orderService)
	orderPublicServer := server.NewOrderPublicServer(httpServer, healthZBiz, orderHandler)
	return orderPublicServer, nil
}
