// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package http_server

import (
	"github.com/huydq/gokits/libs/transport/http"
	"github.com/huydq/gokits/shared/core/biz/healthz"
	"github.com/huydq/order-service/internal/adapter/grpc_client"
	"github.com/huydq/order-service/internal/adapter/persistence/postgres"
	"github.com/huydq/order-service/internal/core/service"
	"github.com/huydq/order-service/internal/transport/http/handler"
	"github.com/huydq/order-service/internal/transport/http/server"
)

// Injectors from wire.go:

func wireApp(httpServer *httpserver.HttpServer, orderPgClient postgres.OrderPostgresClient) (*server.OrderPublicServer, error) {
	healthZBiz := healthz.NewHealthZBiz(httpServer)
	orderRepository := postgres.NewOrderRepository(orderPgClient)
	grpcProductServiceClient := grpc_client.NewGrpcProductMgmtServiceClient()
	orderService := service.NewOrderService(orderRepository, grpcProductServiceClient)
	orderHandler := order_handler.NewOrderHandler(orderService)
	orderPublicServer := server.NewOrderPublicServer(httpServer, healthZBiz, orderHandler)
	return orderPublicServer, nil
}
