// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc_server

import (
	"github.com/huydq/gokits/libs/transport/grpc"
	"github.com/huydq/product-service/app/core/service"
	"github.com/huydq/product-service/transport/grpc/handler"
	"github.com/huydq/product-service/transport/grpc/server"
)

// Injectors from wire.go:

func wireApp(rpcServer *grpc.RPCServer) (*server.ProductGrpcServer, error) {
	productService := service.NewProductService()
	productGrpcHandler := product_handler.NewProductGrpcHandler(productService)
	productGrpcServer := server.NewProductGrpcServer(rpcServer, productGrpcHandler)
	return productGrpcServer, nil
}
